// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1xTXstH6RaSMlhg-vWqRswley2UsZo_Y',
    appId: '1:146215723665:web:1cff4d96bca5c3f639d530',
    messagingSenderId: '146215723665',
    projectId: 'object-detection-4ff08',
    authDomain: 'object-detection-4ff08.firebaseapp.com',
    databaseURL: 'https://object-detection-4ff08-default-rtdb.firebaseio.com',
    storageBucket: 'object-detection-4ff08.appspot.com',
    measurementId: 'G-E84RHRENYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7_WxcDbf3W1JM1PjvSf4X5WwoJssWmbg',
    appId: '1:146215723665:android:c5fe04ed295ac5fe39d530',
    messagingSenderId: '146215723665',
    projectId: 'object-detection-4ff08',
    databaseURL: 'https://object-detection-4ff08-default-rtdb.firebaseio.com',
    storageBucket: 'object-detection-4ff08.appspot.com',
  );

}